version: 0.2

env:
  parameter-store:
    DOCK_REG_USERNAME: /docker-cred/username
    DOCK_REG_PASSWORD: /docker-cred/passwd
  
  phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirement.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - docker login -u $DOCK_REG_USERNAME -p $DOCK_REG_PASSWORD docker.io
      - docker build -t "$DOCK_REG_USERNAME/shivpriya/aws-cicd-success" .
      - docker push "$DOCK_REG_USERNAME/shivpriya/aws-cicd-success"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'