version: 0.2

env:
  parameter-store:
    DOCK_REG_USERNAME: /docker-cred/username
    DOCK_REG_PASSWORD: /docker-cred/passwd
    DOCKER_REG_URL: /docker-cred/url
  phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirement.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCK_REG_PASSWORD" | docker login -u "$DOCK_REG_USERNAME" --password-stdin "$DOCKER_REG_URL"
      - docker build -t "$DOCKER_REG_URL/$DOCK_REG_USERNAME/adi-janu:latest" .
      - docker push "docker.io/shivadmin/adi-janu:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'