version: 0.2

env:
  parameter-store:
    DOCK_REG_USERNAME: /docker-cred/username
    DOCK_REG_PASSWORD: /docker-cred/passwd
    DOCK_REG_URL: /docker-cred/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirement.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCK_REG_USERNAME/$DOCK_REG_URL/success-aws:latest" .
      - docker push "$DOCK_REG_USERNAME/$DOCK_REG_URL/success-aws:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'